name: Keep Replit Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Replit
        run: |
          curl -fsS https://e3b9abdd-5e3f-4fc1-b4bd-9a88cc69d150-00-1kl92thxx1eug.spock.replit.dev// || echo "Ping failed"
